name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      domain: example.com  # TODO: Change to your production domain
