[program:{{DOMAIN}}-horizon]
process_name=%(program_name)s
command=php /home/deployer/sites/{{DOMAIN}}/current/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deployer
numprocs=1
redirect_stderr=true
stdout_logfile=/home/deployer/sites/{{DOMAIN}}/shared/storage/logs/horizon.log
stopwaitsecs=600
