[program:{{DOMAIN}}-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/deployer/sites/{{DOMAIN}}/current/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deployer
numprocs={{NUM_PROCS}}
redirect_stderr=true
stdout_logfile=/home/deployer/sites/{{DOMAIN}}/shared/storage/logs/worker.log
stopwaitsecs=3600
