[{{POOL_NAME}}]
user = deployer
group = deployer

listen = {{FPM_SOCKET}}
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = {{PM_MAX_CHILDREN}}
pm.start_servers = {{PM_START_SERVERS}}
pm.min_spare_servers = {{PM_MIN_SPARE}}
pm.max_spare_servers = {{PM_MAX_SPARE}}
pm.max_requests = 500
pm.process_idle_timeout = 10s

request_terminate_timeout = 60s
request_slowlog_timeout = 5s
slowlog = /var/log/php{{PHP_VERSION}}-fpm-{{POOL_NAME}}-slow.log

catch_workers_output = yes
decorate_workers_output = no

php_admin_value[error_log] = /var/log/php{{PHP_VERSION}}-fpm-{{POOL_NAME}}-error.log
php_admin_flag[log_errors] = on
